name: Run unit tests

on:
  workflow_call:

jobs:
  unittests-:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
